language: go

sudo: false

cache:
  directories:
    - $HOME/chroots

services:
  - docker

env:
  - ARCH=arm

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

addons:
  apt:
    packages:
    - crossbuild-essential-armhf
    - libudev-dev

script:
  - GOARCH=$ARCH go build hello.go
  - ./hello
  - git clone --recursive --branch Release-19.06.02 https://github.com/Seagate/openSeaChest.git
  - cd openSeaChest
  - patch -p1 -i ../ci/openSeaChest-cross_compile.patch
  - cd Make/gcc
  - CC=arm-linux-gnueabihf-gcc AR=arm-linux-gnueabihf-ar LD=arm-linux-gnueabihf-ld make
