language: go

sudo: false

services:
  - docker

env:
  - ARCH=arm

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

script:
  - GOARCH=$ARCH go build hello.go
  - ./hello
