language: go

sudo: false

cache:
  directories:
    - $HOME/chroots

services:
  - docker

env:
  - ARCH=arm

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - wget http://ports.ubuntu.com/pool/main/s/systemd/libudev-dev_229-4ubuntu21.27_armhf.deb
  - sudo dpkg --install libudev-dev_229-4ubuntu21.27_armhf.deb

addons:
  apt:
    packages:
    - crossbuild-essential-armhf

script:
  - GOARCH=$ARCH go build hello.go
  - ./hello
