language: go

sudo: false

cache:
  directories:
    - $HOME/chroots

services:
  - docker

env:
  - ARCH=arm
  - CHROOT_ARCH=armhf
  - MIRROR=http://archive.raspbian.org/raspbian

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - ./ci/prepare-chroot.sh

script:
  - chroot $HOME/chroots/$ARCH bash -c '. envvars.sh && cd $TRAVIS_BUILD_DIR && go build hello.go'
  - chroot $HOME/chroots/$ARCH bash -c '. envvars.sh && cd $TRAVIS_BUILD_DIR && ./hello'
